- frontend/src/utils/checkDataType.js
> fix: 日期时间范围变量值类型错误问题修复 #33

- frontend/src/App.vue
> chore: 出现全局公告时会额外出一个滚动条问题优化 --story=131115507

- frontend/src/views/template/TemplateMock/MockExecute/components/DiffDialog.vue
- frontend/src/views/template/TemplateMock/MockExecute/components/MockRecode.vue
- frontend/src/views/template/TemplateMock/MockExecute/index.vue
> fix: 调试任务交互验收问题修复 --story=120517052

- frontend/src/views/template/TemplateEdit/TemplateSetting/TabTemplateConfig.vue
> fix: 流程通知人保存后未生效问题修复 --story=120397003

- frontend/src/components/DecisionTable/index.vue
> fix: Excel表中没有输出字段 导入展示异常问题修复 #58

- frontend/src/views/admin/Space/DecisionTable/components/DecisionEdit.vue
> fix: 没有配置规则即可创建成功决策表问题修复 --story=130966859

- frontend/src/components/DecisionTable/ImportExport/ExportBtn.vue
> fix: 决策表导出文件名符合蓝鲸规范 --story=130968939

- frontend/package.json
- frontend/src/views/admin/Space/DecisionTable/components/DebugDialog.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/NodeConfig.vue
> fix: 节点配置-jsonSchema表单校验异常问题修复 --ignore

- frontend/src/views/template/TemplateEdit/NodeConfig/InputParams.vue
> fix: 输出参数为空时校验失败问题修复 --ignore

- frontend/src/components/ProcessCanvas/index.vue
- frontend/src/utils/graphJson.js
> fix: 画布交互问题修复 --ignore

- frontend/src/components/SpecialPluginInputForm/ValueAssignPlugin/index.vue
> fix: 节点赋值插件保存字段名修改 --story=121337294

- frontend/src/store/modules/atomForm.js
- frontend/src/views/task/TaskExecute/ExecuteInfo.vue
- frontend/src/views/task/TaskExecute/ExecuteInfo/ExecuteInfoForm.vue
- frontend/src/views/task/TaskExecute/ModifyTime.vue
- frontend/src/views/task/TaskExecute/RetryNode.vue
- frontend/src/views/task/TaskParamEdit.vue
- frontend/src/views/template/TemplateEdit/BatchUpdateDialog.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/src/views/template/TemplateMock/MockExecute/components/TaskParamEdit.vue
- frontend/src/views/template/TemplateMock/MockSetting/index.vue
> fix: 插件支持系统级别配置到特定空间使用 #104

- frontend/src/store/modules/template.js
- frontend/src/views/template/TemplateMock/MockExecute/components/MockRecode.vue
> fix: 模板调试任务列表使用新接口 #111

- frontend/src/store/modules/template.js
- frontend/src/views/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/SelectPanel/apiPlugin.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/SelectPanel/index.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
- frontend/src/views/template/TemplateEdit/index.vue
> fix: API 插件功能优化 #100

- frontend/src/views/admin/Space/SpaceConfig/index.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
> fix: 编辑空间配置表单label名称使用中文 --ignore

- frontend/src/components/DecisionTable/components/TableCell/index.vue
> fix: 决策表单元格值为0时未展示问题修复 --ignore

- frontend/src/views/admin/Space/SpaceConfig/index.vue
> feat: 空间配置编辑支持选择值类型 --ignore

- frontend/src/components/ProcessCanvas/components/tools.vue
- frontend/src/components/ProcessCanvas/index.vue
> fix: 画布节点粘贴bug修复 --story=122536895

- frontend/src/views/template/TemplateEdit/NodeConfig/NodeConfig.vue
- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> fix: 节点配置输出变量勾选保存后，再进行编辑不生效问题修复 --bug=122536817

- frontend/src/components/ProcessCanvas/components/tools.vue
- frontend/src/views/task/TaskExecute/ExecuteInfo.vue
- frontend/src/views/task/TaskExecute/TaskOperation.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/NodeConfig.vue
> fix: 第三方插件执行详情输出展示问题修复 --ignore

- app_desc.yaml
- bkflow/contrib/__init__.py
- bkflow/contrib/expired_cleaner/__init__.py
- bkflow/contrib/expired_cleaner/tasks.py
- bkflow/contrib/expired_cleaner/utils.py
- bkflow/task/celery/settings.py
- env.py
- module_settings.py
> feat: 支持任务清理功能 #141 (#143)

- frontend/src/api/ajax.js
> fix: 添加请求头TRACEPARENT --ignore

- frontend/src/constants/route.js
- frontend/src/views/admin/Plugin/index.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/SelectPanel/plugin.vue
> feat: 蓝鲸插件授权二次确认体验问题修复 --story=122414341

- frontend/src/views/admin/Space/Template/CreateTaskSideslider.vue
> fix: 创建任务表单模式保存参数错误修复 --ignore

- frontend/src/views/admin/Plugin/RangEditDialog.vue
> fix: 插件使用范围编辑-如果已选中后面页的空间，更新选项时会回显异常问题修复 --story=141353228

- frontend/src/components/SpecialPluginInputForm/ValueAssignPlugin/index.vue
- frontend/src/store/modules/template.js
- frontend/src/views/admin/Space/Template/CreateTaskSideslider.vue
- frontend/src/views/admin/Space/Template/index.vue
- frontend/src/views/template/TemplateMock/Header.vue
- frontend/src/views/template/TemplateMock/MockExecute/components/TaskParamEdit.vue
- frontend/src/views/template/TemplateMock/MockExecute/index.vue
> fix: 调试任务-提示变量不存在问题修复 --story=141303685

- frontend/src/views/admin/Space/mixins/tableCommon.js
> fix: 管理端流程搜索时默认回到第一页 --ignore

- bkflow/pipeline_converter/constants.py
- bkflow/pipeline_converter/converters/base.py
- bkflow/pipeline_converter/converters/component.py
- bkflow/pipeline_converter/converters/node.py
- bkflow/pipeline_converter/converters/pipeline.py
- bkflow/pipeline_converter/data_models.py
- tests/pipeline_converter/converters/test_pipeline.py
> feat: 数据转换 DataModel 到 PipelineTree 初步实现 # 184

- bkflow/pipeline_converter/converters/node.py
- bkflow/pipeline_converter/converters/pipeline.py
- tests/pipeline_converter/converters/test_pipeline.py
(cherry picked from commit 7e5faef4637c526debb68ce98573958e77fe90a2)
> fix: fix unit test for data_model to pipeline_tree #184

- frontend/src/components/SpecialPluginInputForm/ValueAssignPlugin/index.vue
> feat: 变量赋值插件添加值类型选项 --ignore

- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/index.vue
> fix: 变量克隆时key值被禁用问题修复 --ignore

- bkflow/pipeline_converter/converters/base.py
- bkflow/pipeline_converter/converters/json_to_data_model/gateway.py
- bkflow/pipeline_converter/converters/json_to_data_model/pipeline.py
- bkflow/pipeline_converter/hub.py
- tests/pipeline_converter/converters/json_to_data_model/test_pipeline.py
> feat: 实现gateway协议json到data_model的转换 #184

- frontend/src/components/SpecialPluginInputForm/ValueAssignPlugin/index.vue
- frontend/src/main.js
- frontend/src/utils/tools.js
- frontend/src/views/task/TaskExecute/ExecuteInfo.vue
- frontend/src/views/template/TemplateEdit/NodeConfig/BasicInfo.vue
> fix: 变量赋值插件描述支持换行渲染 --ignore

- bkflow/pipeline_converter/file_handlers/__init__.py
- bkflow/pipeline_converter/file_handlers/json_handler.py
- bkflow/pipeline_converter/file_handlers/yaml_handler.py
- requirements.txt
> feat: 支持yaml文件导入 #184

- frontend/src/components/ProcessCanvas/components/nodes/index.vue
- frontend/src/components/ProcessCanvas/index.vue
- frontend/src/components/VerticalCanvas/index.vue
- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableItem.vue
- frontend/src/views/template/TemplateEdit/index.vue
> fix: 全局变量添加变量来源跳转icon --ignore

- frontend/package.json
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/dataConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/components/renderHightlightConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/components/renderLinkConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/components/renderProgressConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/renderItem.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/index.vue
- frontend/src/components/canvas/StageCanvas/components/JobNode.vue
- frontend/src/components/canvas/StageCanvas/components/StageNode.vue
- frontend/src/components/canvas/StageCanvas/components/StepNode.vue
- frontend/src/components/canvas/StageCanvas/components/valueRender.vue
- frontend/src/components/canvas/StageCanvas/data.js
- frontend/src/components/canvas/StageCanvas/index.vue
- frontend/src/components/canvas/StageCanvas/utils.js
- frontend/src/store/modules/template.js
- frontend/src/views/template/TemplateEdit/index.vue
- frontend/yarn.lock
> feat: 节点编辑与pipelinetree转换

- frontend/src/store/modules/template.js
> fix: api插件接口请求路径调整 --ignore

- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/dataConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/renderItem.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/index.vue
- frontend/src/components/canvas/StageCanvas/components/JobNode.vue
- frontend/src/components/canvas/StageCanvas/components/StageNode.vue
- frontend/src/components/canvas/StageCanvas/components/StepNode.vue
- frontend/src/components/canvas/StageCanvas/components/valueRender.vue
- frontend/src/components/canvas/StageCanvas/index.vue
- frontend/src/components/canvas/StageCanvas/utils.js
- frontend/src/store/modules/template.js
- frontend/src/views/task/TaskExecute/TaskOperation.vue
- frontend/src/views/template/TemplateEdit/index.vue
> feat: 样式调整、任务状态接口联调

- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/components/renderItem/components/renderLinkConfig.vue
- frontend/src/components/canvas/StageCanvas/components/JobAndStageEditSld/index.vue
- frontend/src/components/canvas/StageCanvas/components/JobNode.vue
- frontend/src/components/canvas/StageCanvas/components/StageNode.vue
- frontend/src/components/canvas/StageCanvas/components/StepNode.vue
- frontend/src/components/canvas/StageCanvas/index.vue
- frontend/src/components/canvas/StageCanvas/utils.js
- frontend/src/store/modules/stageCanvas.js
- frontend/src/store/modules/template.js
- frontend/src/views/template/TemplateEdit/index.vue
> feat: job、stage、node拖拽逻辑

- frontend/src/components/canvas/StageCanvas/index.vue
> fix: 修复任务页面样式问题

- frontend/src/components/canvas/StageCanvas/data.js
- frontend/src/components/canvas/StageCanvas/index.vue
- frontend/src/components/canvas/StageCanvas/utils.js
- frontend/src/store/modules/template.js
> feat: 变量接口联调

- frontend/src/components/canvas/StageCanvas/index.vue
> feat: 请求参数需要将失败节点传给后端

- bkflow/apigw/management/commands/data/api-resources.yml
> fix: 修复网关路径错误 --story=122748567

- config/default.py
> fix: mako模板中的豁免模块去掉json --bug=144422277

- frontend/src/store/modules/template.js
> fix: 修改模板id传参形式 --story=145471637

- config/default.py
> refactor: 打开APM服务 --story=126284031

- bkflow/task/celery/tasks.py
> fix: 修改周期任务计数逻辑 --story=126641235

- frontend/src/store/modules/template.js
- frontend/src/views/template/TemplateEdit/TemplateSetting/TimedTriggerConfig.vue
> fix: cron翻译以及json模式下点击确定无反应 --story=123612043

- frontend/src/components/common/RenderForm/tags/TagInput.vue
- frontend/src/views/template/TemplateEdit/TemplateSetting/TabGlobalVariables/VariableEdit.vue
> fix: 选择变量时增加变量渲染 --story=127499054

- bkflow/pipeline_plugins/components/collections/subprocess_plugin/converter.py
- bkflow/task/serializers.py
> fix: 补充子流程任务缺失字段 --story=127611598
